services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - "5173:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "5001:5000"
    env_file:
      - ./server/.env